### PR TITLE
Issue 421: Update version to 0.3.4

### LINKED ISSUE #421: Prepare 0.3.4 release
**Problem description**
There are some new features and python3.10 support in the pravega python client, it would be good to start a new release.

**Problem location**

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by kotlasaicharanreddy**
**Change log description**  
Update version to 0.3.4

**Purpose of the change**  
Fixes #421 

**What the code does**  
Update version to 0.3.4 to prepare for release.

**How to verify it**  
All tests pass

### CODE REVIEW

**Review by anishakj — APPROVED** [review]
LGTM

**Review by thekingofcity — COMMENTED** [review]
According to the second step of the [release guide in Nodejs](https://github.com/pravega/pravega-client-rust/wiki/Release-guide#release-nodejs-client), the version in package.json should also be updated as well if possible.

**Review by thekingofcity — APPROVED** [review]
LGTM

**Review by tkaitchuck — APPROVED** [review]

**Review by crazyzhou — APPROVED** [review]
lgtm

**Pull request merged**
