### PR TITLE
Removed Python related code changes from the Rust repository

### PR DESCRIPTION
**Pull request by anju-c-das**
The main aim of this change is to segregate the different clients from this repository into dedicated repositories. This change removes the python related client code changes, as the new python client repository is created.

New Python Repo link:  https://github.com/pravega/pravega-client-python/

### CODE REVIEW

**Comment by RaulGracia** [comment]
Thanks @anju-c-das, will the Python binding be installed in the same way it was with the new repository (e.g., via `pip`)? What about the Wiki documents in this repo? Are they going to refer to the new Python binding repo?
cc/ @tkaitchuck

**Comment by anju-c-das** [comment]
Hi @RaulGracia, No currently that part of work is pending in the new python repository. The wiki documents in this repository don't refer to python related code. The new repository contains that information.

**Comment by RaulGracia** [comment]
Thanks @anju-c-das, it may seem obvious, but I would defer this PR until we know that the new Python repository can be released  properly and in such a way that is non disruptive for applications already using it.

**Comment by AnkurAnand11** [comment]
Raised another PR for this https://github.com/pravega/pravega-client-rust/pull/463 .This PR fixes the build failure and removes python related code from rust repo. Hence closing this one.

**Pull request closed without merging**
